const arabicCopy: Record<string, string> = {
  "Profile": "الملف", "complete": "مكتمل", "Useful next additions": "إضافات مفيدة لاحقًا",
  "Target progress": "التقدم نحو الهدف", "coverage": "اكتمال البيانات", "days / week": "أيام أسبوعيًا",
  "Strongest": "أفضل عنصر", "Next focus": "التركيز القادم",
  "Your training story": "رحلتك في التدريب", "PROFILE & PREFERENCES": "الملف والإعدادات",
  "Your goal, assessments and progress, connected in one place.": "هدفك وقياساتك وتقدمك في مكان واحد.",
  "Back to BONYAN": "الرجوع إلى بُنيان", "Sign out": "تسجيل الخروج",
  "Changing your goal or schedule archives your previous plan. Your workout history stays available.": "تغيير هدفك أو جدولك ينقل الخطة السابقة للأرشيف. سجل تمارينك يظل متاحًا.",
  "Choose a week you can repeat.": "اختار جدولًا أسبوعيًا تقدر تستمر عليه.",
  "Close editor": "إغلاق التعديل",
  "How does activity feel today?": "مستوى نشاطك دلوقتي إيه؟",
  "Loading your saved setup…": "جاري استعادة إجاباتك…",
  "Target date · YYYY-MM-DD · optional": "الموعد المستهدف · YYYY-MM-DD · اختياري",
  "These are preparation categories, not a list of official eligibility standards.": "دي فئات للاستعداد، وليست معايير أهلية رسمية.",
  "What can you train with?": "إيه الأدوات المتاحة ليك؟",
  "You can continue without an assessment and add one later.": "تقدر تكمل وتضيف القياسات لاحقًا.",
  "Your reports and measurements stay private. You choose what to share.": "تقاريرك وقياساتك خاصة. أنت تختار ما تشاركه.",
  "Assessment saved to your profile and history.": "تم حفظ التقييم في ملفك وسجلك.",
  "Couldn’t save this assessment. Your entries are still here. Check the values and try again.": "تعذّر حفظ التقييم. إجاباتك موجودة؛ راجع القيم وحاول تاني.",
  "Couldn’t save your changes. Your answers are still here. Please retry.": "تعذّر حفظ التغييرات. إجاباتك موجودة؛ حاول تاني.",
  "Height 80–250 cm · Weight 30–350 kg · Body fat 2–70% when known.": "الطول ٨٠–٢٥٠ سم · الوزن ٣٠–٣٥٠ كجم · الدهون ٢–٧٠٪ عند معرفتها.",
  "Loading your confirmed reports…": "جاري تحميل تقاريرك المؤكدة…",
  "No confirmed report yet. Upload one, review its values, then return here. You can also use manual entry.": "لا يوجد تقرير مؤكد. ارفع تقريرًا وراجع قيمه ثم ارجع هنا، أو استخدم الإدخال اليدوي.",
  "Retry loading reports": "إعادة تحميل التقارير",
  "Continue to training": "متابعة إلى التدريب",
  "Current body assessment": "قياسات الجسم الحالية",
  "Load earlier entries": "تحميل سجلات أقدم",
  "Loading your assessment…": "جاري تحميل تقييمك…",
  "Loading your timeline…": "جاري تحميل سجلك…",
  "Retry assessment": "إعادة تحميل التقييم",
  "Retry history": "إعادة تحميل السجل",
  "You haven’t added an assessment yet. Start with measurements or a confirmed InBody report.": "لم تضف تقييمًا بعد. ابدأ بقياسات يدوية أو تقرير InBody مؤكد.",
  "Your history": "سجلك",
  "Your next assessment or profile update will appear here. Previous entries stay available as you progress.": "التقييم أو التعديل القادم هيظهر هنا، والسجلات القديمة تفضل متاحة.",
  "Close assessment": "إغلاق القياسات", "Add body assessment": "إضافة قياسات الجسم",
  "Hide history": "إخفاء السجل", "Progress & assessment history": "سجل التقدم والتقييمات",
  "Add height and weight. Body fat is optional.": "أضف الطول والوزن. نسبة الدهون اختيارية.",
  "Use a real report you have reviewed and confirmed.": "استخدم تقريرًا حقيقيًا راجعته وأكدت قيمه.",
  "New to a regular training routine.": "تبدأ روتين تدريب منتظم.",
  "Some consistent training experience.": "عندك خبرة في التدريب المنتظم.",
  "Experienced with structured training.": "عندك خبرة كبيرة في التدريب المنظّم.",
  "Add your current ability and a personal target to build your baseline.": "أضف قدرتك الحالية وهدفك الشخصي لتحديد نقطة البداية.",
  "Review your lowest component and choose one achievable next step.": "راجع أقل عنصر تقدمًا واختار خطوة تالية تقدر تنفذها.",
  "reported ability / your personal target": "القدرة المسجلة ÷ هدفك الشخصي",
  "reported active days / planned weekly training days": "أيام النشاط المسجلة ÷ أيام التدريب الأسبوعية المخططة",
  "change from your first assessment toward your selected weight target": "التغير من أول قياس نحو الوزن المستهدف",
  "Push-up target": "هدف الضغط", "Running target": "هدف الجري", "Pull-up target": "هدف العقلة",
  "Weekly consistency": "الانتظام الأسبوعي", "Weight target progress": "التقدم نحو الوزن المستهدف",
  consistency: "الانتظام", endurance: "التحمّل", strength: "القوة", body_composition: "تكوين الجسم",
  beginner: "مبتدئ", intermediate: "متوسط", advanced: "متقدم", starting: "ببدأ", building: "بطوّر لياقتي", established: "لياقتي مستقرة",
  bodyweight: "وزن الجسم", dumbbell: "دمبل", barbell: "بار", machine: "أجهزة", bands: "أشرطة مقاومة",
  military_college: "كلية عسكرية", other: "جهة أخرى", undecided: "لم أحدد بعد",
  height_cm: "الطول · سم", weight_kg: "الوزن · كجم", body_fat_percentage: "نسبة الدهون · ٪", skeletal_muscle_mass_kg: "الكتلة العضلية · كجم",
  assessment: "تقييم الجسم", goal_changed: "تغيير الهدف", profile_updated: "تحديث الملف", onboarding_completed: "اكتمال الإعداد",
  name: "الاسم", goal: "الهدف", experience: "الخبرة", schedule: "الجدول", equipment: "الأدوات", body_data: "قياسات الجسم", military_subtype: "جهة الاستعداد",
  "Manual": "يدوي", "Manual entry": "إدخال يدوي",
};
export function coachingCopy(text: string, arabic = false): string {
  return arabic ? arabicCopy[text] ?? text.replaceAll("_", " ") : text.replaceAll("_", " ");
}
